if (!require("shiny")) install.packages("shiny")
if (!require("shinydashboard")) install.packages("shinydashboard")
if (!require("devtools")) install.packages('devtools')
if (!require("DT")) install.packages('DT', repos = 'http://cran.rstudio.com')
if (!require("htmlwidgets")) install.packages("htmlwidgets")
if (!require("D3TableFilter")) devtools::install_github("ThomasSiegmund/D3TableFilter")
if (!require("signal")) install.packages("signal")
if (!require("data.table")) install.packages("data.table")
library(devtools)
install_github("Rdatatable/data.table", build_vignettes = FALSE)

# install.packages(c("Rcpp", "httpuv", "shiny"))
library(data.table)
library(signal)
library(shiny)
library(shinydashboard)
library(devtools)
library(DT)
library(htmlwidgets)
library(D3TableFilter)
# options(shiny.maxRequestSize = 1000*1024^2)
runApp("F:\\Институт\\Проекты\\EyeTrackingPackage\\Git\\EyeTrackingProject\\Shiny\\AutoUIForSettingsTest")

