if (!require("shiny")) install.packages("shiny")
if (!require("shinydashboard")) install.packages("shinydashboard")
if (!require("devtools")) install.packages('devtools')
if (!require("DT")) install.packages('DT', repos = 'http://cran.rstudio.com')
if (!require("htmlwidgets")) install.packages("htmlwidgets")
if (!require("D3TableFilter")) devtools::install_github("ThomasSiegmund/D3TableFilter")
library(shiny)
library(shinydashboard)
library(devtools)
library(DT)
library(htmlwidgets)
library(D3TableFilter)
# options(shiny.maxRequestSize = 1000*1024^2)
runApp("F:\\Институт\\Проекты\\EyeTrackingPackage\\Git\\EyeTrackingProject\\Shiny")
