source("Functions\\miscFunctions.R", local = T)
source("Functions\\dataLoaders.R", local = T)
source("Classes\\optionsAndSettingsClasses.R", local = T)
source("Classes\\baseEyeDataClasses.R", local = T)
source("Classes\\baseClasses.R", local = T)
source("Classes\\listsAndTablesClasses.R", local = T)
source("Functions\\dataParsers.R", local = T)
source("Functions\\filters.R", local = T)
source("Functions\\smoothers.R", local = T)
source("Functions\\detectors.R", local = T)
source("Functions\\eventAnalyzersNew.R", local = T)
source("Functions\\estimatorsNew.R", local = T)
source("Functions\\DataRecordSubFunctions.R", local = T)
source("Functions\\EventGroupSubFunctions.R", local = T)
source("Methods\\Methods_v_1_7.R", local = T)


