# install.packages("grDevices")
# library(grDevices)
library(signal)
library(data.table)
source("Functions\\readCSVData.R", local = T)
source("Functions\\filters.R", local = T)
source("Functions\\smoothers.R", local = T)
source("Functions\\detectors.R", local = T)
source("Functions\\miscFunctions.R", local = T)
source("Functions\\subFunctions.R", local = T)
source("Functions\\subFunctionsInit.R", local = T)
source("Functions\\movingWindow.R", local = T)
source("Functions\\selectors.R", local = T)

