setwd("F:\\Институт\\Проекты\\EyeTrackingPackage\\Git\\EyeTrackingProject")
source(".\\Functions\\miscFunctions.R")
source(".\\Functions\\dataLoaders.R")
source(".\\Classes\\optionsAndSettingsClasses.R")
source(".\\Classes\\baseEyeDataClasses.R")
source(".\\Classes\\baseClasses.R")
source(".\\Classes\\listsAndTablesClasses.R")
source(".\\Functions\\mainFunctions.R")

source(".\\Functions\\dataParsers.R")
source(".\\Functions\\filters.R")
source(".\\Functions\\smoothers.R")
source(".\\Functions\\detectors.R")
source(".\\Functions\\eventAnalyzers.R")
source(".\\Functions\\estimators.R")
source(".\\Methods\\Methods_v_1_7.R")

